using RiskAware.Server.Data;
using RiskAware.Server.Models;

namespace RiskAware.Server.Seeds
{
    public class RiskHistorySeed
    {
        public static void Seed(AppDbContext context)
        {
            var riskHistoryToBeAdded = new RiskHistory[]
            {
                new()
                {
                    Title = "Špatná komunikace",
                    Description = "Nedostatečná komunikace se zákazníkem.",
                    Probability = 2,
                    Impact = 4,
                    Threat = "Na základě špatné komunikace bude provedena nedostatečná specifikace.",
                    Indicators = "",
                    Prevention = "Koncept",
                    //PreventionDone = DateTime.Parse("2024-04-06 09:00:00"),
                    Status = "Uzavřené",
                    //RiskEventOccured = DateTime.Parse("2024-05-21 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-05 12:00:00"),
                    Created = DateTime.Parse("2024-04-05 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-05 12:00:00"),
                    //End = DateTime.Parse("2024-04-06 09:00:00"),
                    RiskId = 1,
                    UserId = "84c8b270-14e5-4158-bcde-a76c6edc4cf7",
                },
                new()
                {
                    Title = "Špatná komunikace",
                    Description = "Nedostatečná komunikace se zákazníkem.",
                    Probability = 2,
                    Impact = 4,
                    Threat = "Na základě špatné komunikace bude provedena nedostatečná specifikace.",
                    Indicators = "",
                    Prevention = "Ošetření",
                    PreventionDone = DateTime.Parse("2024-04-06 09:00:00"),
                    Status = "Uzavřené",
                    //RiskEventOccured = DateTime.Parse("2024-05-21 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-06 09:00:00"),
                    Created = DateTime.Parse("2024-04-05 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-06 09:00:00"),
                    End = DateTime.Parse("2024-04-06 09:00:00"),
                    RiskId = 1,
                    UserId = "84c8b270-14e5-4158-bcde-a76c6edc4cf7",
                },
                new()
                {
                    Title = "Špatná specifikace požadavků",
                    Description = "Požadavky byly nedostatečně specifikovány/pochopeny/...",
                    Probability = 2,
                    Impact = 5,
                    Threat = "Na základě špatné specifikace bude proveden špatný návrh a nastane zpoždění.",
                    Indicators = "...",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-22 18:00:00"),
                    Status = "Aktivní",
                    //RiskEventOccured = DateTime.Parse("2024-04-08 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-06 12:00:00"),
                    Created = DateTime.Parse("2024-04-06 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-06 12:00:00"),
                    //End = DateTime.Parse("2024-05-24 12:00:00"),
                    RiskId = 2,
                    UserId = "84c8b270-14e5-4158-bcde-a76c6edc4cf7",
                },
                new()
                {
                    Title = "Špatná specifikace požadavků",
                    Description = "Požadavky byly nedostatečně specifikovány/pochopeny/...",
                    Probability = 2,
                    Impact = 5,
                    Threat = "Na základě špatné specifikace bude proveden špatný návrh a nastane zpoždění.",
                    Indicators = "...",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-22 18:00:00"),
                    Status = "Přihodilo se",
                    RiskEventOccured = DateTime.Parse("2024-04-08 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-08 12:00:00"),
                    Created = DateTime.Parse("2024-04-06 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-08 12:00:00"),
                    //End = DateTime.Parse("2024-05-24 12:00:00"),
                    RiskId = 2,
                    UserId = "84c8b270-14e5-4158-bcde-a76c6edc4cf7",
                },
                new()
                {
                    Title = "Modularita návrhu",
                    Description = "...",
                    Probability = 1,
                    Impact = 4,
                    Threat = "...",
                    Indicators = "...",
                    Prevention = "Bez reakce",
                    //PreventionDone = DateTime.Parse("2024-05-25 18:00:00"),
                    Status = "Uzavřeno",
                    //RiskEventOccured = DateTime.Parse("2024-05-25 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-12 11:00:00"),
                    Created = DateTime.Parse("2024-04-09 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-12 11:00:00"),
                    //End = DateTime.Parse("2024-05-26 12:00:00"),
                    RiskId = 3,
                    UserId = "5862be25-6467-450e-81fa-1cac9578650b",
                },
                new()
                {
                    Title = "Nedostatečná modularita návrhu",
                    Description = "...",
                    Probability = 1,
                    Impact = 1,
                    Threat = "...",
                    Indicators = "...",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-25 18:00:00"),
                    Status = "Uzavřeno",
                    //RiskEventOccured = DateTime.Parse("2024-05-25 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-09 12:00:00"),
                    Created = DateTime.Parse("2024-04-09 12:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-09 12:00:00"),
                    //End = DateTime.Parse("2024-05-26 12:00:00"),
                    RiskId = 3,
                    UserId = "5862be25-6467-450e-81fa-1cac9578650b",
                },
                new()
                {
                    Title = "Nesprávné porozumění požadavkům",
                    Description = "Osoba zodpovědná za návrh systému špatně pochopí specifikaci požadavků.",
                    Probability = 1,
                    Impact = 5,
                    Threat = "Bude navrhnut nepožadovaný systém.",
                    Indicators = "",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-28 18:00:00"),
                    Status = "Aktivní",
                    //RiskEventOccured = DateTime.Parse("2024-05-27 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-09 16:42:00"),
                    Created = DateTime.Parse("2024-04-09 16:42:00"),
                    StatusLastModif = DateTime.Parse("2024-04-09 16:42:00"),
                    //End = DateTime.Parse("2024-04-12 12:00:00"),
                    RiskId = 4,
                    UserId = "5862be25-6467-450e-81fa-1cac9578650b",
                },
                new()
                {
                    Title = "Nesprávné porozumění požadavkům",
                    Description = "Osoba zodpovědná za návrh systému špatně pochopí specifikaci požadavků.",
                    Probability = 1,
                    Impact = 5,
                    Threat = "Bude navrhnut nepožadovaný systém.",
                    Indicators = "Špatná specifikace požadavků.",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-28 18:00:00"),
                    Status = "Uzavřeno",
                    //RiskEventOccured = DateTime.Parse("2024-05-27 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-12 11:00:00"),
                    Created = DateTime.Parse("2024-04-09 16:42:00"),
                    StatusLastModif = DateTime.Parse("2024-04-12 11:00:00"),
                    End = DateTime.Parse("2024-04-12 12:00:00"),
                    RiskId = 4,
                    UserId = "5862be25-6467-450e-81fa-1cac9578650b",
                },
                new()
                {
                    Title = "Přetížení zdrojů",
                    Description = "popis rizika",
                    Probability = 2,
                    Impact = 1,
                    Threat = "...",
                    Indicators = "...",
                    Prevention = "Bez reakce",
                    //PreventionDone = DateTime.Parse("2024-05-28 18:00:00"),
                    Status = "Koncept",
                    //RiskEventOccured = DateTime.Parse("2024-05-27 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-12 18:00:00"),
                    Created = DateTime.Parse("2024-04-12 18:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-12 18:00:00"),
                    //End = DateTime.Parse("2024-05-29 12:00:00"),
                    RiskId = 5,
                    UserId = "e81e8eab-2dd2-45ee-8d74-54822c8e69f2",
                },
                new()
                {
                    Title = "Výběr nevhodné platformy",
                    Description = "...",
                    Probability = 1,
                    Impact = 3,
                    Threat = "...",
                    Indicators = "...",
                    Prevention = "Pojištění",
                    //PreventionDone = DateTime.Parse("2024-05-28 18:00:00"),
                    Status = "Koncept",
                    //RiskEventOccured = DateTime.Parse("2024-05-27 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-14 10:00:00"),
                    Created = DateTime.Parse("2024-04-14 10:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-14 10:00:00"),
                    //End = DateTime.Parse("2024-05-29 12:00:00"),
                    RiskId = 6,
                    UserId = "39123a3c-3ce3-4bcc-8887-eb7d8e975ea8",
                },
                new()
                {
                    Title = "Nedostatečná znalost technologií",
                    Description = "...",
                    Probability = 1,
                    Impact = 1,
                    Threat = "Zpoždění kvůli nedostatečné znalosti technologií.",
                    Indicators = "Volba technologií, se kterými osoba zodpovědná za implementaci nemá zkušenosti.",
                    Prevention = "Ošetření",
                    //PreventionDone = DateTime.Parse("2024-05-28 18:00:00"),
                    Status = "Koncept",
                    //RiskEventOccured = DateTime.Parse("2024-05-27 12:00:00"),
                    IsApproved = true,
                    IsValid = true,
                    LastModif = DateTime.Parse("2024-04-18 09:00:00"),
                    Created = DateTime.Parse("2024-04-18 09:00:00"),
                    StatusLastModif = DateTime.Parse("2024-04-18 09:00:00"),
                    //End = DateTime.Parse("2024-05-29 12:00:00"),
                    RiskId = 7,
                    UserId = "12749a7a-100b-4e69-a234-7d059e508d5b",
                }
            };

            foreach (var riskHistory in riskHistoryToBeAdded)
            {
                if (!context.RiskHistory.Any(h => h.Id == riskHistory.Id))
                {
                    context.RiskHistory.Add(riskHistory);
                }
            }
            context.SaveChanges();
        }
    }
}
